
INSERT INTO public.product (
    title,
    handle,
    description,
    is_giftcard,
    status,
    thumbnail,
    discountable
) VALUES
('AMALFI Coona Cover', 'bl-a-dc', 'AMALFI Doona Cover  Colour Charcoal Size King 240x210', false, 'published', 'https://purelinen.com.au/media/catalog/product/b/l/bl_amalfi_charcoal_1.jpg', true),
('AMALFI Fitted Sheet', 'bl-a-fs', 'Amalfi Fitted Sheet Colour Charcoal Size Queen 152x203+50', false, 'published', 'https://purelinen.com.au/media/catalog/product/b/l/bl_amalfi_charcoal_2.jpg', true),
('AMALFI Pillow Case', 'bl-a-p', 'AMALFI Pillow Case Envelope Style Taupe 65x65', false, 'published', NULL, true),
('AMALFI Top Sheet', 'bl-a-ts', 'AMALFI Top Sheet  Colour Taupe Size Queen 250x270', false, 'published', NULL, true),
('Arctic Doona Cover', 'bl-arc-dc', 'Arctic Doona  Colour French Navy Size King 240x210 Made in Australia', false, 'published', NULL, true),
('Arctic Fitted Sheet', 'bl-arc-fs', 'Arctic Fitted Sheet Colour French Navy Size King 180x203+30 Made in Australia', false, 'published', NULL, true),
('Arctic Pillow Case', 'bl-arc-p', 'Arctic Pillow Case <br />Composition 100% linen Colour Arctic Blue <br />Size 65x65  <br />', false, 'published', NULL, true),
('Arctic Top Sheet', 'bl-arc-ts', 'Arctic Top Sheet <br />Composition 100% linen Colour  French Navy <br />Size King <br />Size 280 x 270 <br />', false, 'published', NULL, true),
('Arctic Spring Pillow Case', 'bl-arcs-p', 'Arctic Spring Pillow Case Composition 100% linen Colour Duck Egg Size 65x65', false, 'published', NULL, true),
('Casablanca Bed Cover', 'bl-cas-bc', 'Casablanca Bed Cover - King SIze', false, 'published', NULL, true),
('Diamantina Doona Cover', 'bl-d-dc', 'Diamantina Doona Cover Handmade Hem Stitched Composition 100% linen Colour Optical White Size King 240x210cm', false, 'published', 'https://purelinen.com.au/media/catalog/product/b/l/bl_001_8_1.jpg', true),
('Diamantina Pillow Case', 'bl-d-pc', 'Diamantina Pillow Case Handmade Hem Stitched Composition 100% linen Colour Optical White 73x48', false, 'published', 'https://purelinen.com.au/media/catalog/product/b/l/bl_001_6_1.jpg', true),
('Diamantina Top Sheet', 'bl-d-ts', 'Diamantina Top Sheet Composition 100% linen Colour Optical White King Size 280 x 270', false, 'published', 'https://purelinen.com.au/media/catalog/product/b/l/bl_001_7_1.jpg', true),
('Pure Linen Fitted Sheet', 'bl-ftd', 'Fitted Sheet  Colour Natural  Size King 180x203+50', false, 'published', 'https://purelinen.com.au/media/catalog/product/b/l/bl_002_doona_4.jpg', true),
('Imperial Pillow Case (Set of 2)', 'bl-imp-pc', 'Imperial Pillow Case Damask Hem Stitched Composition 100% linen Colour Sky Blue & Silver Grey Flax Size 65x65', false, 'published', 'https://purelinen.com.au/media/catalog/product/b/l/bl_004_imperial__8_.jpg', true),
('NINGALOO Bed Runner', 'bl-ning-br', 'Ningaloo Bed Runner Stonewashed Blue 100% linen Size 140x220 Printed and made in Australia', false, 'published', NULL, true),
('NINGALOO Doona Cover', 'bl-ning-dc', 'Ningaloo Doona Cover Stonewashed Blue 100% linen Size King 240x210 Printed and made in Australia', false, 'published', NULL, true),
('NINGALOO Pillow Case', 'bl-ning-pc', 'Ningaloo Pillow Case Stonewashed Blue 100% linen Size 48X73 Printed and made in Australia', false, 'published', NULL, true),
('Felice Apron', 'kl-fel-a', 'Felice Apron Stone Washed White', false, 'published', NULL, true),
('NINGALOO Top Sheet', 'bl-ning-ts', 'Ningaloo Top Sheet Stonewashed Blue 100% linen Size King 280x270 Printed and made in Australia', false, 'published', NULL, true),
('Planet Earth Doona Cover', 'bl-pel-dc', 'Planet Earth Doona Cover Composition 100% linen Colour Natural  Size Double 210x180cm', false, 'published', NULL, true),
('Planet Earth Fitted Sheet', 'bl-pel-fs', 'Fitted Sheet Colour Optical White Size King Single 107x203x50', false, 'published', NULL, true),
('Planet Earth Pillow Case - Oxford', 'bl-pel-pc', 'Planet Earth Pillow Case Oxford Style Composition 100% linen Natural 65x65', false, 'published', 'https://purelinen.com.au/media/catalog/product/b/l/bl_002_doona_5.jpg', true),
('Planet Earth Pillow Case - Envelope', 'bl-pel-pce', 'Planet Earth Pillow Case Envelope Style Optical White 48x73', false, 'published', NULL, true),
('Planet Earth Top Sheet', 'bl-pel-ts', 'Planet Earth Top Sheet <br />Composition 100% linen Colour Natural <br />Size King Single <br />Size 200 x 270 <br />', false, 'published', NULL, true),
('Planet Earth Doona Cover', 'bl-pesw-dc', 'Doona Cover Planet Earth Composition 100% linen Stone Washed Colour Eco Natural Size King 240x210 Made in Australia', false, 'published', NULL, true),
('Planet Earth Fitted Sheet', 'bl-pesw-fs', 'Fitted Sheet Composition 100% linen Stone Washed Colour Eco Natural Size King 180x203x50 Made in Australia', false, 'published', NULL, true),
('Planet Earth Pillow Case', 'bl-pesw-pc', 'Pillow Case Plain Envelope Planet Earth Composition 100% linen Stone Washed colour Eco Natural Size 48x73 Made in Australia', false, 'published', NULL, true),
('Planet Earth Top Sheet', 'bl-pesw-ts', 'Top Sheet Planet Earth Composition 100% linen Stone Washed Colour Eco Natural Size King 280x270 Made in Australia', false, 'published', NULL, true),
('Urban LUX Doona Cover', 'bl-ulsw-dc', 'Doona Cover Urban LUX Composition 100% linen Stone Washed Colour Dusty Rose Size King 240x210', false, 'published', NULL, true),
('Urban LUX Fitted Sheet', 'bl-ulsw-fs', 'Fitted Sheet Composition 100% linen Stone Washed Colour Dusty Rose Size Queen 152x203x50', false, 'published', NULL, true),
('KLAIPƒñDA TEA TOWELS', 'kl-klai-tt', 'KLAIPƒñDA TEA TOWELS - Ocean', false, 'published', NULL, true),
('Urban LUX Pillow Case', 'bl-ulsw-pc', 'Pillow Case Urban LUX Composition 100% linen Stone Washed Colour Dusty Rose Size 48x73', false, 'published', NULL, true),
('Urban LUX Top Sheet', 'bl-ulsw-ts', 'Top Sheet Urban LUX Composition 100% linen Stone Washed Colour Dusty Rose Size King 280x270', false, 'published', NULL, true),
('Copenhagen Curtain', 'hd-ch-cu', 'Copenhagen Curtain - White - 146 x 220', false, 'published', NULL, true),
('Copenhagen Curtain', 'hd-cop-cu', 'Copenhagen Curtain - Opal Grey  - 146 x 220', false, 'published', NULL, true),
('Geneva Cushion Cover', 'hd-gen-cu', 'Geneva Cushion Cover  Composition 100% linen Size 45x45 Handcrafted in Australia', false, 'published', 'https://purelinen.com.au/media/catalog/product/h/d/hd_017_9.jpg', true),
('Greige Nature Curtain', 'hd-gr-cu', 'Greige Nature Curtain - 146 x 220', false, 'published', NULL, true),
('GUELL', 'hd-guell', 'Guell Cushions Damask  Hem Stitched Composition 100% linen Colour Natural Flax Size 50x50', false, 'published', 'https://purelinen.com.au/media/catalog/product/h/d/hd_guell_cu65_1.jpg', true),
('Hamptons Curtain', 'hd-hamp-c', 'Hamptons Curtain - Persian Blue- 146 x 300', false, 'published', NULL, true),
('Irma Throws', 'hd-irma', 'Irma Throw French Grey - Stripes & Checks Composition 100% linen Size 130x200', false, 'published', 'https://purelinen.com.au/media/catalog/product/h/d/hd_irma_ab_04.jpg', true),
('Venetian Lace Cushion Cover', 'hd-lace', 'Venetian Lace Cushions White with Natural Embroidery Composition 100% linen Size 45 x 45', false, 'published', 'https://purelinen.com.au/media/catalog/product/h/d/hd_020_lace_19_.png', true),
('La Marseillaise Curtain', 'hd-lam-c', 'La Marseillaise tie-top Curtain with  Hand-made Hem Stitch Colour Optical White Size 146x260 Composition 100% Linen  Hand-Made in Russia with Love&Care', false, 'published', NULL, true),
('Marta Cushions', 'hd-mar-cu', 'Marta Cushion Collection', false, 'published', 'https://purelinen.com.au/media/catalog/product/h/d/hd_marta_brown.jpg', true),
('Montigny-le-Roi Cushion Cover', 'hd-mlr-cu', 'Montigny-le-Roi Cushion Cover  Colour Natural with Blue embroidery Composition 100% linen Size 45x45', false, 'published', 'https://purelinen.com.au/media/catalog/product/h/d/hd_mlr_mlrnb.jpg', true),
('Monk''s Cloth Cushion Covers', 'hd-mnk-cu', 'Monk''s Cloth Cushion covers with triple fringes Composition 100% damask linen Hand-made in Perth Australia Size 50x50 cm', false, 'published', NULL, true),
('NINGALOO Cushion', 'hd-ning-cu', 'NINGALOO Cushion Cover 60 x 60', false, 'published', NULL, true),
('Osaka Cushion Cover', 'hd-osa-cu', 'Osaka Cushion Cover Natural with White Embroidery <br />Composition 100% linen <br />Size 45x45 <br />', false, 'published', 'https://purelinen.com.au/media/catalog/product/h/d/hd_019_osaka__2_.jpg', true),
('RIGA Curtains', 'hd-riga-c', 'RIGA Curtain - Natural - 146 x 300', false, 'published', NULL, true),
('Sejero Curtain', 'hd-s-c', 'Sejero Curtain - Cobalt- 146 x 220', false, 'published', NULL, true),
('Sejero Cushion Cover', 'hd-sej-cc', 'SEJERO Cushion - Pearl Blue 45 x 45 Plain', false, 'published', NULL, true),
('Sejero Curtain', 'hd-sej-cu', 'Sejero Curtain - Denim - 146 x 220', false, 'published', NULL, true),
('Symphony Knitted Curtain', 'hd-sym-cu', 'Symphony Knitted Curtain Composition 100% linen Colour Natural Flax Size 90x220', false, 'published', NULL, true),
('Tallinn Curtain', 'hd-talin-cu', 'Tallinn Curtain Plain Composition 100% linen Colour Natural Flax Size 270x220', false, 'published', NULL, true),
('Tokyo Cushion Cover', 'hd-tok-cc', 'Tokyo Cushion Cover White with Silver Embroidery Composition 100% linen Size 45x45', false, 'published', 'https://purelinen.com.au/media/catalog/product/h/d/hd_018_tokyo__5_.jpg', true),
('Urban Curtain', 'hd-u-cu', 'Urban Curtain - White - 270W x 220L', false, 'published', NULL, true),
('Urban Lux Cushion Cover', 'hd-ul-cc', 'URBAN LUX Cushion Cover Natural Flax 45 x 45 with Piping', false, 'published', NULL, true),
('Urban Lux Curtain', 'hd-ul-cu', 'Urban Lux Curtain - Opal Grey - 270 x 220', false, 'published', NULL, true),
('Versailles Cushion', 'hd-v-cc', 'Versailles Cushions Damask Size 50x25 Composition 56%linen/44%cotton Size 50x178', false, 'published', 'https://purelinen.com.au/media/catalog/product/h/d/hd_013__2_.jpg', true),
('Bertha Tea Towels', 'kl-ber-tt', 'Bertha Tea Towels Natural Flax & Indigo Borders Composition 100% linen Size 50x80', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/e/new_bertha_tea_towels__2.jpg', true),
('Caglitari Tea Towel', 'kl-cag-tt', 'Caglitari Tea Towels Colour Oyster Size 42x70', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_cag_oyster_tt_1.jpg', true),
('EDGAR Apron', 'kl-edg-a', 'Edgar Apron with bib Eco Natural Composition 100% linen Handcrafted in Australia from  European Linen fabric', false, 'published', NULL, true),
('French Motif Tea Towels', 'kl-fm-tt', 'Beautiful 100% linen', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_frenchmotif_blue_1000_1_1_1_1.jpg', true),
('HERITAGE Apron', 'kl-he-ap', 'Heritage linen apron Natural', false, 'published', NULL, true),
('IN STYLE Tea Towel', 'kl-is-tt', 'In Style Tea Towels Colour Pearl Blue Size 50 X 70 cm Composition 100% Linen Softened and Pre-shrunk (pack by 3- price per unit $9+GST; price per pack $27+GST)', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_is_pearlblue_3.jpg', true),
('Le Coq Tea Towels', 'kl-lec-tt', 'Le Coq Tea Towels Red Jacquard Composition 100% linen Size 50x80', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_le_coq_red_1_1.jpg', true),
('LESUEUR Tea Towel', 'kl-les-tt', 'LESUEUR Tea Towel - Denim 50 x 70', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_is_denim_2.jpg', true),
('Modern Classic Tea Towel', 'kl-mc-tt', 'Modern Classic Tea Towel Single Hem Stitched Colour Eco Natural Flax Size 45 x 85', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_modernclassic_natural_tt_1.jpg', true),
('Olives Tea Towels', 'kl-oli-tt', 'Olives Tea Towels Lilac Borders Jacquard  Composition 56%linen/44%cotton Size 50x70 cm', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_olives_blue_1000_4_2.jpg', true),
('Pure Linen Glass Cloth Tea Towels', 'kl-pl-tt', 'Pure Linen Glass Cloth Tea Towel White & Natural Border Composition 56%linen/44%cotton Size 50x80', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_purelinen_hero_08_2.jpg', true),
('STOCKHOLM Tea Towels', 'kl-st-tt', 'STOCKHOLM Tea Towel Plain Optical White Composition 100% Linen Soften & Pre-Shrunk Size 50 X 70 cm', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_stockholm-1_2.jpg', true),
('Trattoria Tea Towels', 'kl-t-tt', 'Trattoria Tea Towels Composition 56%linen/44%cotton Colour Blue & White Size 50x70', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_cc_hero_01_1_3.jpg', true),
('Tuscan Napkins', 'kl-tus-n', 'Tuscan Napkins Poppy flower  Composition 100% Linen Size 42x42', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_001__4_.jpg', true),
('AMALFI Tablecloth', 'na-a-t', 'AMALFI Tablecloth Colour Taupe Size Round Diameter 270', false, 'published', NULL, true),
('ALBANY Napkin', 'na-alb-n', 'ALBANY Napkins with hemstitched detail Sky Blue/Flax 45X45 cm Composition 100% Linen', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_hugo_1000x1500_1.jpg', true),
('AMALFI Cocktail Napkin', 'na-am-cn', 'AMALFI Cocktail Napkins Colour Taupe Size 22x22', false, 'published', NULL, true),
('AMALFI Napkins', 'na-am-n', 'AMALFI Napkins Colour Taupe Size 60x60', false, 'published', NULL, true),
('AMALFI Placemats', 'na-am-p', 'AMALFI Placemats Colour Taupe Size  35x50', false, 'published', NULL, true),
('AMALFI Runners', 'na-am-r', 'AMALFI Runner Colour Taupe Size  50x180', false, 'published', NULL, true),
('AMALFI Tablecloths', 'na-am-t', 'AMALFI Tablecloth Colour Taupe Size 180x400', false, 'published', NULL, true),
('KLAIPĖDA Coasters', 'na-klai-co', 'KLAIPĖDA COASTERS Hunter', false, 'published', NULL, true),
('Bertha Napkins', 'na-ber-n', 'Bertha Napkins Colour Natural Flax & Bronze Borders Composition 100% linen Size 50x50', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_bertha_product_02.jpg', true),
('CAGLITARI Napkin', 'na-cag-n', 'CAGLITARI napkin - Colour Rose Quartz - 45 x 45', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_cag_rosequartz_1.jpg', true),
('CAGLITARI Runner', 'na-cag-r', 'CAGLITARI runner - Colour Rose Quartz - 42 x 180', false, 'published', NULL, true),
('Diamantina Cocktail Napkin', 'na-d-cn', 'Diamantina Cocktail Napkin Handmade Hem Stitched Colour Optical White Size 22 x 22', false, 'published', NULL, true),
('Diamantina Napkins', 'na-d-n', 'Diamantina Napkins Handmade Hem Stitched Composition 100% linen Colour Optical White Size 50x50', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_diamantina_white_1000x1500_1.jpg', true),
('Diamantina Placemat', 'na-d-p', 'Diamantina Placemats Handmade Hem Stitched Colour Optical White Size 35x50', false, 'published', NULL, true),
('Diamantina Runner', 'na-d-r', 'Diamantina Runner Handmade Hem Stitched Colour Optical White Size 50x 180', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_diam_hero_02_1.jpg', true),
('Diamantina Tablecloth', 'na-d-t', 'Diamantina Tablecloth Colour Optical White Round Diameter 180', false, 'published', NULL, true),
('CALYPSO DOTS Napkin', 'na-dots-n', 'CALYPSO DOTS Napkin Colour Black Size 50X50', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_dots_black_1.jpg', true),
('CALYPSO DOTS Placemat', 'na-dots-p', 'CALYPSO DOTS Placemat Colour Black Size 30X50', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_dots_black_2.jpg', true),
('CALYPSO DOTS Runner', 'na-dots-r', 'CALYPSO DOTS Runner Colour Black Size 50x180', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_dots_black_3.jpg', true),
('CALYPSO DOTS Tablecloth', 'na-dots-t', 'CALYPSO DOTS Tablecloth Colour Black Round Diameter 180', false, 'published', NULL, true),
('Eco Planet Napkins', 'na-eco-n', 'Eco Planet Napkins Colour Eco Natural Flax Size 43x43 cm  Composition 100% Linen Proudly Handmade in Perth Australia', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_ecop_n_napkin_1.jpg', true),
('ESPERANCE Napkins', 'na-es-n', 'ESPERANCE Champagne Napkin 45x45 cm Composition 100% Linen', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_esperance_champagne.jpg', true),
('Felice Tablecloths', 'na-fel-t', 'Product group NA_FEL with variant TCN500/2', false, 'published', NULL, true),
('French Melody Runner', 'na-fme-r', 'French Melody Runner Damask Hem Stitched Colour Natural Composition 100% linen Size 50X150 cm', false, 'published', 'https://purelinen.com.au/media/catalog/product/k/l/kl_frenchmelody_tt_1_1.jpg', true),
('French Motif Napkins', 'na-fmo-n', 'Napkins French Motif Damask Colour Wedgwood Blue  Hem Stitched Composition 100% linen Size 45x45', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_024__frenchmotif_84_.jpg', true),
('Harmony Tablecloth', 'na-ha-t', 'Harmony Tablecloth Size 178x350', false, 'published', NULL, true),
('Harmony Tablecloth', 'na-har-t', 'Harmony Tablecloth Composition 56%linen/44%cotton Size 178x178', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_harmony_02_1.jpg', true),
('Heritage Napkins', 'na-he-n', 'Heritage Napkins Composition 100% linen Colour  Natural Size 50x50', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_bistro_04_800x_3.jpg', true),
('Heritage Tablecloths', 'na-he-t', 'Heritage Tablecloth Composition 100% linen Colour  Natural Size 180x180', false, 'published', NULL, true),
('Heritage Runners', 'na-he-r', 'Heritage Runner Colour Black Size 50X180 Composition 100% Linen', false, 'published', NULL, true),
('Heritage Placemats', 'na-he-p', 'Heritage Placemats  Colour Black Size 35X50 Composition 100% Linen', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_bistro_03_800x_1.jpg', true),
('Heritage Coasters', 'na-he-co', 'Heritage Coasters Colour Optical White Size  12X12 cm Composition 100% Linen', false, 'published', NULL, true),
('Heritage Cocktail Napkins', 'na-he-cn', 'Heritage Cocktail Napkins Colour Oyster Size 22x22', false, 'published', NULL, true),
('In Style Napkins', 'na-is-n', 'In Style Napkins', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_is_navy_1.jpg', true),
('In Style Tablecloth', 'na-is-t', 'In Style Tablecloth Colour Opal Grey Plain Style Size 146x146', false, 'published', NULL, true),
('KLAIPĖDA Cocktail Napkins', 'na-klai-cn', 'KLAIPĖDA COCKTAIL NAPKINS Bayberry-22x22', false, 'published', NULL, true),
('KLAIPĖDA Napkins', 'na-klai-n', 'KLAIPĖDA NAPKINS - Bayberry-45x45', false, 'published', NULL, true),
('KLAIPĖDA Placemats', 'na-klai-p', 'KLAIPĖDA PLACEMATS Bayberry', false, 'published', NULL, true),
('KLAIPĖDA Runners', 'na-klai-r', 'KLAIPĖDA RUNNERS Bayberry-46 x 180', false, 'published', NULL, true),
('Marta Placemat', 'na-mar-p', 'The Marta Placemat Collection', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_037_marta_0015_4.jpg', true),
('KLAIPĖDA Tablecloths', 'na-klai-t', 'KLAIPƒñDA TABLECLOTHS Bayberry-146 X 180', false, 'published', NULL, true),
('Ladoga Napkins', 'na-l-n', 'Ladoga Napkins Hemstitched Composition 100% linen Colour Optical White Size 50x50', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_024_ladoga__7_.jpg', true),
('Mimosa Napkins', 'na-m-n', 'Mimosa Napkins Hemstitched and Hand Embroidered Composition 100% linen Colour Optical White Size 50x50', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_mimosa_napkin.jpg', true),
('Mimosa Placemat', 'na-m-p', 'Mimosa Placemats Hemstitched and Hand Embroidered Composition 100% linen Colour Optical White Size 35x50', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_mimosa_pm_1.jpg', true),
('Mimosa Runner', 'na-m-r', 'Mimosa Runner Hemstitched and Hand Embroidered Composition 100% linen Colour Optical White Size 50x180', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_mimosa_1000_4_2.jpg', true),
('Mimosa Tablecloth', 'na-m-t', 'Mimosa Tablecloth Hemstitched and Hand Embroidered Composition 100% linen Colour Optical White Size 180x180', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_mimosa_tc_1000_003.jpg', true),
('Marta Runner', 'na-mar-r', 'Marta Runner Collection', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_037_marta_0013_3.jpg', true),
('Modern Classic Tablecloth', 'na-mc-t', 'Modern Classic Tablecloth Single Hem Stitched Colour Optical White Size 142x320', false, 'published', NULL, true),
('Modern Classic Double Hem Stitched Placemats', 'na-mcd-p', 'Modern Classic Placemats Double Hem Stitched Composition 100% linen Colour Charcoal Size 35x50 Composition 100% linen', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_mcd_pm_char.jpg', true),
('Modern Classic Herringbone Napkins', 'na-mch-n', 'Modern Classic Napkins Herringbone  Hem Stitched Persian Blue Composition 100% linen Size 45x45', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_mchb_03.jpg', true),
('Modern Classic Single Hem Stitched Napkins', 'na-mcs-n', 'Modern Classic Napkins Single Hem Stitched Composition 100% linen Colour  Charcoal Size 45 x 45', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_mcshs_na_1.jpg', true),
('Monks Cloth Napkin', 'na-mnk-n', 'Monks Cloth Napkin Composition 100% linen Size 50x50 Made in Australia', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_041_monks_0003.jpg', true),
('Monks Cloth Placemat', 'na-mnk-p', 'Monks Cloth Placemat Composition 100% linen Size 35x50 Made in Australia', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_041_monks_0001_1_1.jpg', true),
('Monks Cloth Runner', 'na-mnk-r', 'Monks Cloth Runner Composition 100% linen Size 50x180 Made in Australia', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_monks_napkin_1000x1500_1.jpg', true),
('Monks Cloth Tablecloth', 'na-mnk-t', 'Monks ClothTablecloth Composition 100% linenSize 150x150 Made in Australia', false, 'published', NULL, true),
('Morning Dreams Tablecloth', 'na-mor-t', 'Morning Dreams Tablecloth Cranberry & Cranberry Composition 56%linen/44% cotton Size 178x178', false, 'published', 'https://purelinen.com.au/media/catalog/product/m/o/morningdreamsc_c2.jpg', true),
('NINGALOO Napkin', 'na-ning-n', 'Ningaloo Napkins Stonewashed Blue 100% linen Size 43x43 Printed and made in Australia', false, 'published', NULL, true),
('NINGALOO Placemat', 'na-ning-p', 'Ningaloo Placemats Stonewashed Blue 100% linen Size 35x50 Printed and made in Australia', false, 'published', NULL, true),
('NINGALOO Runner', 'na-ning-r', 'NINGALOO Runner Stonewashed Blue 100% linen Size 42 x 200 Printed and made in Australia', false, 'published', NULL, true),
('NINGALOO Tablecloth', 'na-ning-t', 'Ningaloo Tablecloth Stonewashed Blue 100% linen Size 140x140 Printed and made in Australia', false, 'published', NULL, true),
('Planet Earth Tablecloths', 'na-pe-t', '<p><strong>Planet Earth Tablecloths With Fringes</strong></p>', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_planetearth_1000_4.jpg', true),
('Picnic Napkins', 'na-pic-n', 'Picnic Tablecloth Composition 100% cotton Size 140x350', false, 'published', NULL, true),
('Pure Linen Glass Cloth Napkins', 'na-pur-n', 'Pure Linen Glass Cloth Napkins White &  Black Border Composition 56%linen/44%cotton Size 50x50', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_purelinen_009_3.jpg', true),
('Silver Birch Cocktail Napkins', 'na-sb-cn', 'Silver Birch Cocktail Napkins Hemstitched Composition 100% linen Colour Optical White Size 22x22 cm', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_silverbirch_1000x1500_1.jpg', true),
('Scandinavia Table Centrepiece', 'na-sca-t', 'Scandinavia Table Centrepiece Natural Flax Composition 100% linen size 90x90', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_018_3.jpg', true),
('Sorrento Napkins', 'na-so-n', 'Sorrento Napkins Colour White & Blue Stripe Size 50x50', false, 'published', NULL, true),
('Turkey Placemats', 'na-t-p', 'Turkey Placemats Terracotta Jacquard Size 58x32cm', false, 'published', 'https://purelinen.com.au/media/catalog/product/t/u/turkey_placemat_001s.jpg', true),
('Trattoria Napkins', 'na-tr-n', 'Trattoria Napkins  Composition 56%linen/44%cotton Size 45x45 Colour Blue & White', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_cc_b_nap.jpg', true),
('Trattoria Tablecloths', 'na-tr-t', 'Trattoria Tablecloth Composition 56% linen/44% cotton  Colour Natural & White Size 150X180', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_006_countrychecks__19_.jpg', true),
('Trees Runner', 'na-tre-r', 'Trees Runner Black with Hem Stitch Composition 100% linen Size 50x150', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_trees_1000_2_1.jpg', true),
('Tuscan Tablecloth', 'na-tus-t', 'Tablecloth Tuscan Wheat Composition 100% Linen Size 140x250', false, 'published', NULL, true),
('Urban Cocktail Napkin', 'na-u-cn', 'Urban Cocktail Napkin Natural Flax Size 22x22  Made in Australia', false, 'published', NULL, true),
('Urban Napkin', 'na-u-n', 'Urban Placemat White Size 35x50 Made in Australia', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_urban_white_hero_01_4.jpg', true),
('Urban Placemant', 'na-u-p', 'Urban Placemats Natural Flax Size 35x50 Made in Australia', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_urban_natural_hero_01_4.jpg', true),
('Urban Runner', 'na-u-r', 'Urban Runner Natural Flax Size 50x180 Made in Australia', false, 'published', NULL, true),
('Urban Tablecloth', 'na-u-t', 'Urban Tablecloth Natural Flax Size Diameter 180cm Made in Australia', false, 'published', NULL, true),
('URBAN LUX Cocktail Napkin', 'na-ul-cn', 'URBAN LUX Cocktail Napkin Dusty Rose Size 22x22cm Made in Australia', false, 'published', NULL, true),
('URBAN LUX Coaster', 'na-ul-co', 'URBAN LUX Coaster Dusty Rose Size 10x10cm Made in Australia', false, 'published', NULL, true),
('URBAN LUX Napkin', 'na-ul-n', 'URBAN LUX Napkin Dusty Rose Size 45x45 cm Proudly Handmade in Perth Australia', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_ubanlux_dusty_02_3.jpg', true),
('URBAN LUX Placemat', 'na-ul-p', 'URBAN LUX Placemats Dusty Rose Size 35x50 Made in Australia', false, 'published', 'https://purelinen.com.au/media/catalog/product/n/a/na_ubanlux_dusty_02_1.jpg', true),
('URBAN LUX Runner', 'na-ul-r', 'URBAN LUX Runner Dusty Rose Size 50x180 Made in Australia', false, 'published', NULL, true),
('URBAN LUX Tablecloth', 'na-ul-t', 'Steel Grey', false, 'published', NULL, true),
('Versailles Tablecloth', 'na-ver-t', 'Versailles Tablecloth Damask Composition 56%linen/44% cotton Size 178x178', false, 'published', NULL, true);

-- End of product insert statements
